version: '2'

services:
  portainer:
    image:  portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

volumes:
  portainer_data:
